### ISSUE TITLE
if directory of recording exists but not the file or the file exists but its length == 0 the recorder silently fails

### ISSUE THREAD

**Issue by mottykohn** [lassana/continuous-audiorecorder#12]
The issue lies in the following code:
`            if (targetFile.exists() && targetFile.length() > 0) {
                String tmpFileName = mainFileName + ".tmp";
                append(mainFileName, anotherFileName, tmpFileName);
                copyFile(tmpFileName, mainFileName);
                rvalue = anotherFile.delete() && new File(tmpFileName).delete();
            } else if (targetFile.getParentFile().mkdirs() && targetFile.createNewFile()) {
                copyFile(anotherFileName, mainFileName);
                rvalue = anotherFile.delete();
            } 
`
`mkdirs()` returns false if directory exists so does `createNewFile()` if file exists.

**Comment by lassana** [comment]
Should be fixed in #13.
