### ISSUE TITLE
Get amplitude or frequency spectrum

### ISSUE THREAD

**Issue by NerdGr8** [lassana/continuous-audiorecorder#16]
Hi guys, i was wondering how I could use this and also implement an audio record visualizer of some sort.

**Comment by lassana** [comment]
Hello!
The visualizer is out of scope of this project, so I would recommend to look at the soundrecorder from AOSP - [platform_packages_apps_soundrecorder](https://github.com/android/platform_packages_apps_soundrecorder). Probably [`VUMeter.java`](https://github.com/android/platform_packages_apps_soundrecorder/blob/master/src/com/android/soundrecorder/VUMeter.java) is what you looking for.
