### ISSUE TITLE
Error when click quickly to record and pause 

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [lassana/continuous-audiorecorder#2]
When user click quickly on record and pause buttons app close activity and return without any crash report 
the problem here 
private void appendToFile(final String targetFileName, final String newFileName) {
        Mp4ParserWrapper.append(targetFileName, newFileName);//<- here 
    }

when user click quickly append function doesn't finish appending so app crash but not show any exception stacktrace 
thanks for sharing this lib

**Comment by lassana** [comment]
Done
