### ISSUE TITLE
The filename suffix is MP3, but in fact his encoding is AAc

### ISSUE THREAD

**Issue by heraldxy** [lassana/continuous-audiorecorder#23]
I use your example，I gave him the file name in MP3 format,But the fact is the AAC format，How to make him a real MP3 format?

**Comment by lassana** [comment]
There is no way to do this with the library (and there is no mp3 encoder in the Android API: [link](https://developer.android.com/reference/android/media/MediaRecorder.AudioEncoder.html)). I can only suggest to use `ffmpeg` to convert recorded audio to mp3 files.
