### ISSUE TITLE
how to save recorded audio file in sdcard?

### ISSUE THREAD

**Issue by hmahdavi921** [lassana/continuous-audiorecorder#3]
Hi.I try save recorded audio file in   sdcard/mypath but I can not do this.Please advice

**Comment by lassana** [comment]
You should use something like this:

    String sdcardFilename = Environment.getExternalStorageDirectory()
                + File.separator
                + "Record_"
                + System.currentTimeMillis()
                + ".mp4";
    AudioRecorder recorder = AudioRecorder.build(context, sdcardFilename);
    recorder.start(listener);

Don't forget about permissions:

    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
