### ISSUE TITLE
Error : Start Failed

### ISSUE THREAD

**Issue by loikfb** [lassana/continuous-audiorecorder#4]
11-05 21:54:12.126 2156-2172/com.apptest.fr.myapptest W/EGL_emulation: eglSurfaceAttrib not implemented
11-05 21:54:12.126 2156-2172/com.apptest.fr.myapptest W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xad7bdb40, error=EGL_SUCCESS
11-05 21:54:12.219 2156-2172/com.apptest.fr.myapptest E/Surface: getSlotFromBufferLocked: unknown buffer: 0xabf11a60
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime: Process: com.apptest.fr.myapptest, PID: 2156
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:309)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:  Caused by: java.lang.RuntimeException: setAudioSource failed.
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at android.media.MediaRecorder.setAudioSource(Native Method)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at com.github.lassana.recorder.AudioRecorder$StartRecordTask.doInBackground(AudioRecorder.java:89)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at com.github.lassana.recorder.AudioRecorder$StartRecordTask.doInBackground(AudioRecorder.java:79)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
11-05 21:54:21.704 2156-2378/com.apptest.fr.myapptest E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818) 
11-05 21:54:21.851 2156-2384/com.apptest.fr.myapptest E/MediaRecorder: stop called in an invalid state: 0
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity: Audio Recorder error !
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity: java.lang.IllegalStateException
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity:     at android.media.MediaRecorder.stop(Native Method)
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity:     at com.github.lassana.recorder.AudioRecorder$PauseRecordTask.doInBackground(AudioRecorder.java:125)
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity:     at com.github.lassana.recorder.AudioRecorder$PauseRecordTask.doInBackground(AudioRecorder.java:117)
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-05 21:54:22.104 2156-2156/com.apptest.fr.myapptest E/MainActivity:     at java.lang.Thread.run(Thread.java:818)
11-05 21:54:22.119 2156-2172/com.apptest.fr.myapptest E/Surface: getSlotFromBufferLocked: unknown buffer: 0xabf11ad0
11-05 21:54:26.907 2156-2156/com.apptest.fr.myapptest I/Choreographer: Skipped 287 frames!  The application may be doing too much work on its main thread.
11-05 21:54:27.267 2156-2163/com.apptest.fr.myapptest W/art: Suspending all threads took: 84.007ms
11-05 21:54:28.923 2156-2378/? I/Process: Sending signal. PID: 2156 SIG: 9

**Comment by lassana** [comment]
Is [the sample app](https://drone.io/github.com/lassana/continuous-audiorecorder/files) working on your device?
Do you have `RECORD_AUDIO` permission in your app?

**Comment by loikfb** [comment]
Yes a have the permission in my Manifest but I don't know how to import this .apk file in android studio to test it on my device.. I continue to try this. I also tried to add the new dependencie 1.1.0 with the new builder in my project but it print a similar stack trace than the first one.

**Comment by loikfb** [comment]
I continue testing your continuousAudioRecorder with my project and I figured out that it just failed with devices api level 23 but the sample app works well with 23 ... I don't really understand difference between the sample app and when we compile with contiuousAudioRec dependencie, if there is any, will you update the target api to Marshmallow ?

**Comment by lassana** [comment]
The library doesn't handle a new run-time permission system, you should do it in your code.
Smth like [this](https://github.com/lassana/continuous-audiorecorder/blob/runtime-permissions/sample/src/main/java/com/github/lassana/continuous_audiorecorder/fragment/MainFragment.java#L169).

**Comment by loikfb** [comment]
Thank you for your help, now I can understand my mistake and I already fixed it.
