### ISSUE TITLE
Location of the recording file?

### ISSUE THREAD

**Issue by MostafaNasiri** [lassana/continuous-audiorecorder#7]
Where is the recorded audio file located? how can i move it to another location?

**Comment by lassana** [comment]
The library allows set the filename: [`public AudioRecorderBuilder fileName(@NonNull String targetFileName)`](https://github.com/lassana/continuous-audiorecorder/blob/master/recorder/src/main/java/com/github/lassana/recorder/AudioRecorderBuilder.java#L28).
